version: "3.9"

services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./network_data.db:/app/network_data.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload